"""Add nomor_hp, tanggal_lahir, jenis_kelamin to users

Revision ID: 4e603884befa
Revises: 83fca2665fb0
Create Date: 2024-12-11 19:16:19.725901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e603884befa'
down_revision = '83fca2665fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nomor_hp', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('tanggal_lahir', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('jenis_kelamin', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('jenis_kelamin')
        batch_op.drop_column('tanggal_lahir')
        batch_op.drop_column('nomor_hp')

    # ### end Alembic commands ###
