"""create users table

Revision ID: 4eef27130ef6
Revises: 402ef53d7d92
Create Date: 2024-11-19 00:57:30.635441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4eef27130ef6'
down_revision = '402ef53d7d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('superadmin', 'admin', 'public', name='user_roles'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('superadmin', 'admin', 'public', name='user_roles'),
               type_=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
