"""Add nama_user column to users

Revision ID: 83abca90aaed
Revises: 4eef27130ef6
Create Date: 2024-11-19 01:10:56.485142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83abca90aaed'
down_revision = '4eef27130ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_user', sa.String(length=100), nullable=False))
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('superadmin', 'admin', 'public'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('superadmin', 'admin', 'public'),
               nullable=True)
        batch_op.drop_column('nama_user')

    # ### end Alembic commands ###
