"""Tambah kolom gambar

Revision ID: a83f722ad4ee
Revises: f2d57b5bbd42
Create Date: 2024-12-25 22:39:52.128736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a83f722ad4ee'
down_revision = 'f2d57b5bbd42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('profile_picture',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('published_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_column('featured_image')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('featured_image', mysql.VARCHAR(length=300), nullable=True))
        batch_op.alter_column('published_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('profile_picture',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
