"""Add table Alamat

Revision ID: b496936fb3ea
Revises: a83f722ad4ee
Create Date: 2025-01-12 13:02:17.968461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b496936fb3ea'
down_revision = 'a83f722ad4ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alamat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provinsi', sa.String(length=100), nullable=False),
    sa.Column('kabupaten_kota', sa.String(length=100), nullable=False),
    sa.Column('kecamatan', sa.String(length=100), nullable=False),
    sa.Column('desa', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('kode_pos', sa.String(length=10), nullable=False),
    sa.Column('alamat_lengkap', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alamat')
    # ### end Alembic commands ###
